# Chill Models

**1.Run the chilling() function on the Winters_hours_gap dataset**

```{r}
chilling_output <- chilling(make_JDay(Winters_hours_gaps),Start_JDay = 90, End_JDay = 100)
chilling_output
```

**2.Create your own temperature-weighting chill model using the step_model() function.**

```{r}
own_utah_steps <- data.frame(
  lower=c(-291,0,1,2,3,4,5,6),
  upper=c(0,1,2,3,4,5,6,100),
  weight=c(0,0.5,1,2,3,2,1,0))

kbl(own_utah_steps, escape = F) %>%
  kable_paper("hover", full_width = F, position = "left")

own_utah <- function(x) step_model(x,own_utah_steps)

test <- own_utah(Winters_hours_gaps$Temp)

```

**3.Run this model on the Winters_hours_gaps dataset using the tempResponse() function.**

```{r}
output<-tempResponse(make_JDay(Winters_hours_gaps),
                     Start_JDay = 90, End_JDay = 100, 
                     models=list(Own_Utah_Model=own_utah, Chill_portions=Dynamic_Model),
                     whole_record = TRUE)
kable(output) %>%
  kable_styling("striped", position = "left", font_size = 10)
```

------------------------------------------------------------------------