# Historic temperature scenarios

**1. For the location you chose for previous exercises, produce historic temperature scenarios representing several years of the historic record (your choice).**
```{r Loading packages and data, echo=FALSE, message=FALSE}
require(chillR)
require(ggplot2)
fixed_weather <- read.csv("data/CapeTown_weather.csv")
weather_CapeTown <- fixed_weather
```

```{r Generating 4x100 years of weather of the past, eval=FALSE}
scenario_2001<-temperature_scenario_from_records(weather=weather_CapeTown,year=2001)
scenario_2001

all_past_scenarios<-temperature_scenario_from_records(
  weather=weather_CapeTown,
  year=c(1985, 1995, 2005, 2015)) #creating absolute scenarios for those years

adjusted_scenarios<-temperature_scenario_baseline_adjustment(
  baseline=scenario_2001,
  temperature_scenario = all_past_scenarios) #transforming to relative with bl 96

all_past_scenario_temps<-temperature_generation(
  weather=weather_CapeTown,
  years=c(1982,2020),
  sim_years=c(2001,2100),
  temperature_scenario = adjusted_scenarios)
```

```{r Saving all past scenario temperatures, echo=FALSE, eval=FALSE}
save_temperature_scenarios(all_past_scenario_temps,"data","past_scenario_temps")
```

```{r Loading all past scenarios, echo=FALSE}
all_past_scenario_temps <- load_temperature_scenarios("data","past_scenario_temps")
```

**2. Produce chill distributions for these scenarios and plot them.**
```{r Calculating chill for all past scenarios}
chill_hist_scenario_list<-tempResponse_daily_list(all_past_scenario_temps,
                                                  latitude=-34.10835247406239,
                                                  Start_JDay = 121,
                                                  End_JDay = 243)

scenarios<-names(chill_hist_scenario_list)[1:4]

all_scenarios<-chill_hist_scenario_list[[scenarios[1]]]
all_scenarios[,"scenario"]<-as.numeric(scenarios[1])


for (sc in scenarios[2:4])
 all_scenarios<-rbind(all_scenarios,
                      cbind(chill_hist_scenario_list[[sc]],scenario=as.numeric(sc)))

all_scenarios<-all_scenarios[which(all_scenarios$Perc_complete==100),]


actual_chill<-tempResponse_daily_list(weather_CapeTown,latitude=-34.10835247406239,
                                                  Start_JDay = 121,
                                                  End_JDay = 243)[[1]]
actual_chill<-actual_chill[which(actual_chill$Perc_complete==100),]
```


```{r Plotting the past chill portions in a violin ggplot}
ggplot(data=all_scenarios,aes(scenario,Chill_Portions,
                              fill=factor(scenario))) +
  geom_violin() +
  ylab("Chill accumulation (Chill Portions)") +
  xlab("Scenario year") +
  theme_bw(base_size=15) +
  ylim(c(0,90)) +
  geom_point(data=actual_chill,
             aes(End_year,Chill_Portions,fill="blue"),
             col="blue",show.legend = FALSE) +
  scale_fill_discrete(name="Scenario",
                      breaks = unique(all_scenarios$scenario)) 
```

