# Future temperature scenarios

**1. Analyze the historic and future impact of climate change on three agroclimatic metrics of your choice, for the location you’ve chosen for your earlier analyses.**
```{r, echo=FALSE}
require(chillR)
require(ggplot2)
fixed_weather <- read.csv("data/CapeTown_weather.csv")
weather_CapeTown <- fixed_weather
summary(weather_CapeTown)

RCPs<-c("rcp45","rcp85")
Times<-c(2050,2085)
```


```{r, eval=FALSE}
RCPs<-c("rcp45","rcp85")
Times<-c(2050,2085)


for(RCP in RCPs)
  for(Time in Times)
    {start_year <- Time-15
     end_year <- Time+15
     clim_scen <-getClimateWizardData(
     c(longitude = 18.93521767626777,latitude = -34.10835247406239),
     RCP,
     start_year,
     end_year,
     temperature_generation_scenarios = TRUE,
     baseline =c(1977, 2005),
     metric = "monthly_min_max_temps",
     GCMs = "all")
   save_temperature_scenarios(clim_scen,
                              "data/ClimateWizard",
                              paste0("CapeTown_futures_",Time,"_",RCP))}

```

```{r, eval=FALSE}
scenario_1991<-temperature_scenario_from_records(weather_CapeTown,1991) #median of 1977 and 2005
scenario_1998<-temperature_scenario_from_records(weather_CapeTown,1998) #median of 1977 and 2019
adjustment_scenario<-temperature_scenario_baseline_adjustment(scenario_1998,scenario_1991)
adjustment_scenario
```

```{r, eval=FALSE}
RCPs<-c("rcp45","rcp85")
Times<-c(2050,2085)

for(RCP in RCPs)
  for(Time in Times)
    {
     clim_scen<-load_ClimateWizard_scenarios(
       "data/climateWizard",
       paste0("CapeTown_futures_",Time,"_",RCP))
     clim_scen_adjusted<-
       temperature_scenario_baseline_adjustment(
         baseline_temperature_scenario=adjustment_scenario,
         temperature_scenario=clim_scen)
     Temps<-temperature_generation(
       weather=weather_CapeTown,
       years=c(1977,2019),
       sim_years=c(2001,2101),
       temperature_scenario = clim_scen_adjusted)

     save_temperature_scenarios(
       Temps,
       "data/Weather",
       paste0("CapeTown_",Time,"_",RCP))
  }
```

```{r, eval=FALSE}
all_past_scenarios<-temperature_scenario_from_records(
  weather=weather_CapeTown,
  year=c(1980,1990,2000,2010))

adjusted_scenarios<-temperature_scenario_baseline_adjustment(
  baseline=scenario_1998,
  temperature_scenario = all_past_scenarios) #ensure relative climate

all_past_scenario_temps<-temperature_generation(
  weather=weather_CapeTown,
  years=c(1977,2019),
  sim_years=c(2001,2101),
  temperature_scenario = adjusted_scenarios)

save_temperature_scenarios(
  all_past_scenario_temps,
  "data/Weather",
  "CapeTown_historic")
```

```{r, eval=FALSE}
frost_model<-function(x) step_model(x,data.frame(
  lower=c(-1000,0),
  upper=c(0,1000),
  weight=c(1,0)))

models<-list(Chill_CP=Dynamic_Model,Heat_GDH=GDH,Frost_H=frost_model)



Temps<-load_temperature_scenarios("data/Weather","CapeTown_historic")
chill_past_scenarios<-tempResponse_daily_list(
  Temps,
  latitude=-34.10835247406239,
  Start_JDay = 121,
  End_JDay = 243,
  models=models,
  misstolerance = 10)
chill_observed<-tempResponse_daily_list(
  weather_CapeTown,
  latitude=-34.10835247406239,
  Start_JDay = 121,
  End_JDay = 243,
  models=models,
  misstolerance = 10)

save_temperature_scenarios(chill_past_scenarios,
                           "data/chill",
                           "CapeTown_historic")
save_temperature_scenarios(chill_observed,
                           "data/chill",
                           "CapeTown_observed")
```

```{r, eval=TRUE}
chill_past_scenarios<-load_temperature_scenarios(
  "data/chill",
  "CapeTown_historic")
chill_observed<-load_temperature_scenarios(
  "data/chill",
  "CapeTown_observed")

chills <-make_climate_scenario(
  chill_past_scenarios,
  caption = "Historic",
  historic_data = chill_observed,
  time_series = TRUE)

plot_climate_scenarios(
  climate_scenario_list=chills,
  metric="Chill_CP",
  metric_label="Chill (Chill Portions)")
```

```{r, eval=FALSE}
for(RCP in RCPs)
  for(Time in Times)
    {
    Temps<-load_temperature_scenarios(
      "data/Weather",
      paste0("CapeTown_",Time,"_",RCP))
    chill<-tempResponse_daily_list(
      Temps,
      latitude=-34.10835247406239,
  Start_JDay = 121,
  End_JDay = 243,
      models=models,
      misstolerance = 10)
    save_temperature_scenarios(
      chill,
      "data/chill",
      paste0("CapeTown_",Time,"_",RCP))
}
```

```{r}
for(RCP in RCPs)
  for(Time in Times)
    {
    chill<-load_temperature_scenarios(
      "data/chill",
      paste0("CapeTown_",Time,"_",RCP))
    if(RCP=="rcp45") RCPcaption <- "RCP4.5"
    if(RCP=="rcp85") RCPcaption <- "RCP8.5"
    if(Time=="2050") Time_caption <- "2050"
    if(Time=="2085") Time_caption <- "2085"
    chills <-make_climate_scenario(
      chill,
      caption =c(RCPcaption, Time_caption),
      add_to = chills)
}
```

```{r}
plot_climate_scenarios(
  climate_scenario_list=chills,
  metric="Chill_CP",
  metric_label="Chill (Chill Portions)",
  texcex=1.5)

plot_climate_scenarios(
  climate_scenario_list=chills,
  metric="Heat_GDH",
  metric_label="Heat (Growing Degree Hours)",
  texcex=1.5)

plot_climate_scenarios(
  climate_scenario_list=chills,
  metric="Frost_H",
  metric_label="Frost hours",
  texcex=1.5)
```

