---
title: "Untitled"
author: "Julian Bauer"
date: '2022-10-29'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(knitr)
library(kableExtra)
library(formattable)
library(dplyr)
library(chillR)
```



```{r, echo=FALSE}
require(leaflet) 
m <- leaflet() %>% setView(lng = 18.877782 , lat = -33.924805, zoom = 16)
m %>% addProviderTiles(providers$Esri.WorldImagery) %>%
  addMiniMap(
    tiles = providers$Esri.WorldStreetMap,
    toggleDisplay = TRUE)

require(chillR)
library(kableExtra)
```

```{r, message=FALSE, warning=FALSE}
station_list<-handle_gsod(action="list_stations",
                          location=c(18.877782, -33.924805),
                          time_interval=c(1990,2020),
                          stations_to_choose_from = 25)

station_list

```




## R Markdown

```{r}
ft_dt <- mtcars[1:5, 1:4]
ft_dt$car <- row.names(ft_dt)
row.names(ft_dt) <- NULL
ft_dt$mpg <- color_tile("white", "orange")(ft_dt$mpg)
ft_dt$cyl <- cell_spec(ft_dt$cyl, angle = (1:5)*60, 
                      background = "red", color = "white", align = "center")
ft_dt$disp <- ifelse(
  ft_dt$disp > 200,
  cell_spec(ft_dt$disp, color = "red", bold = T),
  cell_spec(ft_dt$disp, color = "green", italic = T)
)

kbl(ft_dt, escape = F) %>%
  kable_paper("hover", full_width = F) %>%
  column_spec(5, width = "3cm") %>%
  add_header_above(c(" ", "Hello" = 2, "World" = 2))
```

```{r}

hourtemps <- subset(Winters_hours_gaps, select = -c(Temp_gaps))

hourtemps <- hourtemps[1:5, 1:5]
hourtemps$Year <- row.names(hourtemps)
row.names(hourtemps) <- NULL
hourtemps$Hour <- color_tile("white", "orange")(hourtemps$Hour)
hourtemps$Month <- cell_spec(hourtemps$Month, angle = (1:5)*60, 
                      background = "red", color = "white", align = "center")
hourtemps$Temp <- ifelse(
  hourtemps$Temp > 200,
  cell_spec(hourtemps$Temp, color = "red", bold = T),
  cell_spec(hourtemps$Temp, color = "green", italic = T)
)

kbl(hourtemps, escape = F) %>%
  kable_paper("hover", full_width = F) %>%
  column_spec(5, width = "3cm") %>%
  add_header_above(c(" ", "Hello" = 2, "World" = 2))

```

```{r}

hourtemps <- subset(Winters_hours_gaps, select = -c(Temp_gaps))

hourtemps <- hourtemps[4008:4012, 1:5]

hourtemps$Temp <- ifelse(
  hourtemps$Temp > 20,
  cell_spec(hourtemps$Temp, color = "red", bold = T),
  cell_spec(hourtemps$Temp, color = "green")
)

kbl(hourtemps, escape = F) %>%
  kable_paper("hover", full_width = F)


```
